name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create config.js from secret
        run: |
          echo "${{ secrets.CONFIG_JS }}" > config.js
          echo "--- config.js の中身確認 ---"
          cat config.js
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHAT_A23CE }}
          channelId: live
          projectId: chat-a23ce